### ISSUE TITLE
Time to cut a new release? 

### ISSUE THREAD

**Issue by gregory** [octet-stream/form-data#12]
Hey @octet-stream, looks like a [lot happened](https://github.com/octet-stream/form-data/compare/v1.8.1...octet-stream:master) since the latest version published on npm. 
I was trying to use your lib to solve for form-data/form-data#394 but looks like 1.8.1 doesn't support options. 
Can you cut a new release?

**Comment by octet-stream** [comment]
Hi!
You can actually get the latest version from GitHub until I'll publish the next release. I was trying to hold one until the [Node 8 end of life](https://github.com/nodejs/release#release-schedule) so I can drop it. The next release will be 2.0, so I think it's a good time for it :)
But yeah, I think the new release is almost done, so I can publish it at soon.

**Comment by octet-stream** [comment]
Okay, I think it's ready to use.
You can try out the 2.0.0 version from NPM/Yarn

Release note can be found here: https://github.com/octet-stream/form-data/releases/tag/v2.0.0
