### ISSUE TITLE
File fields are not instances of Blob

### ISSUE THREAD

**Issue by jaydenseric** [octet-stream/form-data#14]
A [`File`](https://developer.mozilla.org/en-US/docs/Web/API/File) field should be an instance of [`Blob`](https://developer.mozilla.org/en-US/docs/Web/API/Blob) when read via [`FormData.get()`](https://developer.mozilla.org/en-US/docs/Web/API/FormData/get).

For example, in Chrome:

<img width="592" alt="Screen Shot 2020-02-03 at 11 18 12 pm" src="https://user-images.githubusercontent.com/1754873/73652911-1fe3e580-46dc-11ea-8bfe-43e39526b436.png">

I'm trying to assert in a project that a `Blob` instance (globally polyfilled via [`fetch-blob`](https://github.com/node-fetch/fetch-blob)) gets correctly added to a `FormData` instance, and one of the things to check is that the type of the field that was added is a `Blob`.

**Comment by octet-stream** [comment]
Please read the [docs](https://github.com/octet-stream/form-data#getname---string--readable--readstream--readablestream--file):
> Returns the first value associated with the given name. If the field has Blob, Buffer or any Readable and ReadableStream (and when options.size is set for this stream) value, the File-like object will be returned.

I don't polyfill anything, instead I use objects which have same methods and properties as those from browsers API. It allows you to use your own Blob and File implementations if they're compatible.
If you want to check whether returning field is a Blob, File or ReadableStream, you must check it other way than just call `instanceof`.
See: [`util/isWHATWGReadable.mjs`](https://github.com/octet-stream/form-data/blob/73d5f4dbffab6f6a27f26c6611e32662c98c2891/src/lib/util/isWHATWGReadable.mjs#L13-L21) and [`util/isBlob`](https://github.com/octet-stream/form-data/blob/73d5f4dbffab6f6a27f26c6611e32662c98c2891/src/lib/util/isBlob.mjs#L16-L24)

Just to mention, this is how node-fetch handles the same checks: [`utils/is.js`]()

**Comment by jaydenseric** [comment]
That may be how it works now, but it could be better.

- If `Blob` global is present, use it, otherwise use a local `Blob` class.
- If `File` global is present, use it, otherwise extend `Blob` (either from a global or a local class, see above) to create and use a local `File` class.

**Comment by octet-stream** [comment]
Now that's sounds good to me. I will take a look at that. Thanks again!

**Comment by octet-stream** [comment]
hey, looks like fetch-blob has `[Symbol.hasInstance](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/hasInstance)`, so the `myFile instanceof Blob` should work.

**Comment by jaydenseric** [comment]
Hmm, this used to not work so maybe something changed 🤔

`instanceof Blob` is working now in my tests, so the original reason for this issue is resolved. I'll leave it up to you to close it or not here, because I'm not sure how anything other than the [originally suggested fix](https://github.com/octet-stream/form-data/issues/14#issuecomment-581401935) could resolve other potential issues.

**Comment by octet-stream** [comment]
Hi @jaydenseric 👋
I think since Node.js [has the first class Blob support](https://nodejs.org/dist/latest/docs/api/buffer.html#buffer_class_blob), I can integrate this package with fetch-blob and eventually add native Blob support.

**Comment by octet-stream** [comment]
So, this change available in https://github.com/octet-stream/form-data/releases/tag/v3.0.0. I believe this issue is now resolved.

**Comment by octet-stream** [comment]
Also, note that public API has been changed, so be careful and read release note before upgrading :)
