### ISSUE TITLE
Remove FormData.toJSON()

### ISSUE THREAD

**Issue by jaydenseric** [octet-stream/form-data#2]
In browsers `FormData` instances don't have `.toJSON`:

<img width="460" alt="screen shot 2019-02-12 at 10 57 18 pm" src="https://user-images.githubusercontent.com/1754873/52633827-a9be0000-2f19-11e9-96be-5f4ea6079c92.png">

For consistency with browsers it would be nice to remove that from the API here:

https://github.com/octet-stream/form-data/blob/10bf4e653bfe990f1537d4e3bbd66d5b8bb45ea8/src/lib/FormData.mjs#L405

Specifically, this logic:

```js
const form = new FormData()
form.append('a', 'b')

const replacer = (key, value) => typeof FormData !== 'undefined' && value instanceof FormData
    ? 'works'
    : value

console.log(JSON.stringify(form, replacer))
```

Logs `works` in a browser, but `[object FormData]` when importing `FormData` from `formdata-node` in Node.js. This is because when a value has `.toJSON()`, `JSON.stringify` provides the output of that instead of the original value to the replacer function.

I would like to be able to use this package to test some `FormData` related code that is mostly intended to run in browsers. 

A workaround is to do this instead:

```js
function replacer(key) {
  const value = this[key]
  // …
```

But then I am changing code to match this library instead of the native `FormData` API.

**Comment by octet-stream** [comment]
Sounds reasonable. Sure, I can remove that. Thanks for your feedback!

**Comment by octet-stream** [comment]
Done! Try v1.3.1

**Comment by jaydenseric** [comment]
Looks good 🙌
