### ISSUE TITLE
Non-existtent fields, null or undefined?!

### ISSUE THREAD

**Issue by laszbalo** [octet-stream/form-data#26]
Hi,

just tested this in Chrome and Firefox. In their implementation, the form data objects return null on non-existent fields. Your implementation returns undefined. Is this intentional?

https://github.com/octet-stream/form-data/blob/eb5daf38368089627a3285673d0aaef8d99fb394/test/FormData/get.js#L20

**Comment by octet-stream** [comment]
Hi!
Yeah, my mistake. I'll fix that.

**Comment by octet-stream** [comment]
Published with the https://github.com/octet-stream/form-data/releases/tag/v2.4.0

**Comment by laszbalo** [comment]
Thank you!
