### ISSUE TITLE
Create a one time deprecation warning

### ISSUE THREAD

**Issue by jimmywarting** [octet-stream/form-data#41]
...if they append Buffer or Streams and that it will be gone in v4
https://github.com/octet-stream/form-data/blob/fd7f6b18a8c6abb9c1dc7341ebb5846a0551bff0/lib/FormData.ts#L162-L167

**Comment by octet-stream** [comment]
formdata-node already has these deprecation warnings on both `.append()` and `.set()` methods. See: https://github.com/octet-stream/form-data/blob/fd7f6b18a8c6abb9c1dc7341ebb5846a0551bff0/lib/FormData.ts#L276-L277

![image](https://user-images.githubusercontent.com/7884558/129233884-c4398731-9388-470b-941c-8fa9454c3087.png)

**Comment by octet-stream** [comment]
By the way I am thinking to create an issue in formdata-node repo with v4 roadmap to bring what would change in v4 to developers attention as you did in node-fetch...

**Comment by jimmywarting** [comment]
Ah, missed that
