### ISSUE TITLE
`browser` field

### ISSUE THREAD

**Issue by char0n** [octet-stream/form-data#47]
I've noticed that the `browser` field is defined in following way:

```
"browser": "./lib/cjs/browser.js"
```

Wouldn't it make more sense to point the field to `./lib/esm/browser.js`? I know the file doesn't have any imports, so it doesn't really matter if it's CJS or ESM, but looks odd to be pointing to CJS.

**Comment by octet-stream** [comment]
Browser field is here for backwards compatibility and will be removed as I move to ESM only (near Node.js v12 EOL).
I also have `module` field that points to esm version of this module, for bundlers.

**Comment by char0n** [comment]
Sure, but for example in webpack, browser field gets priority over module field - https://webpack.js.org/configuration/resolve/#resolvemainfields. This effectively means that CJS version of formdata is being bundled instead of ESM one.

**Comment by octet-stream** [comment]
Don't Webpack read `export` first?

**Comment by char0n** [comment]
Yes, webpack@5 reads `exports`, and then fallback to `browser`. webpack@4 (everything running on create react app) uses `browser` field and ignores `exports` field.

**Comment by char0n** [comment]
It's no big deal, just IMHO pointing `browser` field to ESM build makes more sense as webpack@4 is still very widely used. I can issue a PR.

**Comment by octet-stream** [comment]
I don't really see any reason for this change if webpack can deal with it. Browser field will be removed anyway in the nearest future and there's almost no content in `browser.ts`

**Comment by char0n** [comment]
Right, I've just pointed to this and thought that it might be oversight.
