### ISSUE TITLE
 throw new Error(`.git can't be found (see ${url})`)

### ISSUE THREAD

**Issue by gregory** [octet-stream/form-data#51]
As [advised](https://github.com/typicode/husky/issues/851#issuecomment-777179899) here, could you rename [postinstall](https://github.com/octet-stream/form-data/blob/master/package.json#L65) to _postinstall

**Comment by octet-stream** [comment]
Probably I need to inform developers to `husky install` manually in readme? I would rather want it to work without asking to install something manually.

**Comment by octet-stream** [comment]
Closed for the same reason as #52.
