### ISSUE TITLE
Append part of file only, not the whole file

### ISSUE THREAD

**Issue by leopucci** [octet-stream/form-data#56]
Hey there! Nice work so far!

` formData.set('file', fileFromPathSync(filePath),0,1024);//just first 1024 bytes`

Do you know how could I append to the form only some part of the file without buffering on the heap?

**Comment by jimmywarting** [comment]
fileFromPathSync returns a standard web File class (aka blob)
you don't actually read anything into memory by using it - you only stat the file size and last modified date and making a references point to where it can read from/to.

```js
// nothing is held in memory (just a references point)
const file = fileFromPathSync(path)

// nothing is held in memory (just a references point \w a offset to where to start reading from and stopping)
const blobSlice = file.slice(0, 1024, file.type)

formData.set('file', chunk)
```

**Comment by octet-stream** [comment]
The fileFromPath function creates regular File, so you can slice it like that:

```js
const file = fileFromPathSync(filePath) // This will create a reference to file on disk and not actually read that.

form.set("file", file.slice(0, 1024), file.name) // .slice() will return Blob, so don't forget to provide a name in a third argument, if you want to keep it
```

**Comment by leopucci** [comment]
Thank you @jimmywarting and @octet-stream!

**Comment by leopucci** [comment]
Cool. Seems to be the best way to do it. 
Thanks @jimmywarting !

**Comment by leopucci** [comment]
He @jimmywarting and @octet-stream. File slice is working ok and I am being able to send part of a file on a stream. 

But I am having trouble with accentuation çéáíó 

I was using 

```
const file = fileFromPathSync(filePath) 
form.set("file", file.slice(0, 1024), file.name) 
```


So i changed some chars to try to get this properly. 

```
formData.set(
              'file',
              file.slice(0,1024),
              Buffer.from(file.name, 'utf-8').toString()
            );
```

Either way I am not getting the name correctly at the server side. Do you guys think on something about it?
The strange thing is that on the other formData fields i am sending the same names but they arrive on the server correctly
![image](https://user-images.githubusercontent.com/38509299/169718983-266987bb-16dc-4567-8f78-7b7fa648ef81.png)


I´m starting to think that this is not a form-data problem but on server side

**Comment by leopucci** [comment]
I´m having this behaviour even with postman app, so it does not seems to be the form-data field that is messing with the server.

**Comment by leopucci** [comment]
Solved!
It was at the other side. 
For some reason parameters was utf8 but for filenames the charset was latin1. 
Have a nice week @jimmywarting and @octet-stream
