### ISSUE TITLE
ERR_PACKAGE_PATH_NOT_EXPORTED in version 5.0.1

### ISSUE THREAD

**Issue by Joshua-alt** [octet-stream/form-data#64]
No "exports" main defined in /home/joshua/Documents/softProjet/authapigun-master/node_modules/formdata-node/package.json

**the version [4.4.1](https://www.npmjs.com/package/formdata-node/v/4.4.1) work fine and don't have this error. I use nodejs18**

**Comment by octet-stream** [comment]
Hi. Thanks for the feedback. How can I reproduce it? I have created a minimal project with `formdata-node@5.0.1` (installed via pnpm), and I don't see the problem.

**Comment by Joshua-alt** [comment]
don’t module try to import as const {File}=require(“FormData-mode”)

**Comment by octet-stream** [comment]
This shouldn't work, because formdata-node does not support CJS starting from 5.x
If use need CJS, then either stay on 4.x version or import the package using [dynamic `import()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import) syntax.

**Comment by HiroYuan-DAICHIGP** [comment]
Same here for v5.0.1 with Node version 16.
Downgrade to 4.4.1 resolved this issue.

**Comment by octet-stream** [comment]
v6 brings back CJS support and it's available now, check out release notes for more information: https://github.com/octet-stream/form-data/releases/tag/v6.0.0
