### ISSUE TITLE
Support for Fetch API

### ISSUE THREAD

**Issue by ThallesP** [octet-stream/form-data#67]
Currently, the form-data is not compatible with node Fetch API

![image](https://github.com/octet-stream/form-data/assets/76017384/4f5e1a10-afb9-4c48-b69b-e30c57377988)

**Comment by octet-stream** [comment]
Hi. Sorry for the late response. Your issue might be related to https://github.com/octet-stream/form-data/issues/57

However, if you use formdata-node with globally available fetch, it should be compatible with globally available `BodyInit` type when v6 is released.

**Comment by octet-stream** [comment]
I'm closing this as a duplicate, please track progress in #57.
